In [ ]:
import numpy as np
import pandas as pd


In [ ]:
#1D array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#2D array
b=np.array([[1,2,3,4],[5,6,7,8]])
b
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#3D array
c=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]], dtype=np.float128)
c
print(c)
print(c.dtype)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]]
float128


In [ ]:
c.shape


(1, 3, 4)

In [ ]:
c.size

12

In [ ]:
c.itemsize

16

In [ ]:
c.max()

12.0

In [ ]:
c.min()

1.0

In [ ]:
c.sum()

78.0

In [ ]:
c.std()

3.4520525295346631888

In [ ]:
c.mean()

6.5

In [ ]:
c.var

<function ndarray.var>

In [ ]:
np.sqrt(c)

array([[[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]], dtype=float128)

In [ ]:
X=np.array([1,2,3,4,5])
Y=np.array([1,2,3,4,5])
print(X+Y)

[ 2  4  6  8 10]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a>5)

[False False False False False  True  True  True  True  True]


In [ ]:
print(a==5)

[False False False False  True False False False False False]


In [ ]:
only_ones = np.ones((3,4))
print(only_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
only_zeros = np.zeros((3,4))
print(only_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
only_ones = np.ones((4,3,4))
print(only_ones)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
ran = np.random.random((5,5))
print(ran)

[[0.34151565 0.45069417 0.88448888 0.08768751 0.26582379]
 [0.25180913 0.48533245 0.90934085 0.55707146 0.58950414]
 [0.77332144 0.19288941 0.8020478  0.08010293 0.73406147]
 [0.38246806 0.51580829 0.07041893 0.81309574 0.17177781]
 [0.02638829 0.94710585 0.13474058 0.58933326 0.25872081]]


In [ ]:
ran = np.random.randint(100,size=(5,5))
print(ran)

[[11 68 10 11 94]
 [57 11 64 19  4]
 [50 85 40 40 22]
 [ 5  0  6 48 48]
 [65 54 45 89 93]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a=a.reshape(3,2)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
l2=np.random.randint(21,30,size=(5,5))
print(l2)

[[26 23 29 27 23]
 [22 25 23 27 26]
 [23 25 26 24 27]
 [24 23 29 22 25]
 [26 27 29 21 22]]


In [ ]:
l4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(l4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
l4[1:3,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
df2 = pd.DataFrame(np.array([[2,5,3],[4,5,6],[7,8,10]]))
print(df2)
print(df2.shape)

   0  1   2
0  2  5   3
1  4  5   6
2  7  8  10
(3, 3)


In [ ]:
df2.isnull()

0      1      2
0  False  False  False
1  False  False  False
2  False  False  False

In [ ]:
df2.isnull().sum()

0    0
1    0
2    0
dtype: int64

In [ ]:
df2.describe()

0         1          2
count  3.000000  3.000000   3.000000
mean   4.333333  6.000000   6.333333
std    2.516611  1.732051   3.511885
min    2.000000  5.000000   3.000000
25%    3.000000  5.000000   4.500000
50%    4.000000  5.000000   6.000000
75%    5.500000  6.500000   8.000000
max    7.000000  8.000000  10.000000

In [ ]:
df2.corr()

0         1         2
0  1.000000  0.917663  0.999466
1  0.917663  1.000000  0.904194
2  0.999466  0.904194  1.000000

from matplotlib import pyplot as plt
_df_11[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_12[1].plot(kind='hist', bins=20, title=1)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_13[2].plot(kind='hist', bins=20, title=2)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_14.plot(kind='scatter', x=0, y=1, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_15.plot(kind='scatter', x=1, y=2, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_16[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_17[1].plot(kind='line', figsize=(8, 4), title=1)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_18[2].plot(kind='line', figsize=(8, 4), title=2)
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df2[0]#colomn

0    2
1    4
2    7
Name: 0, dtype: int64

In [ ]:
df2[[0,2]]

0   2
0  2   3
1  4   6
2  7  10

from matplotlib import pyplot as plt
_df_19[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_20[2].plot(kind='hist', bins=20, title=2)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_21.plot(kind='scatter', x=0, y=2, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[0]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 0}, axis=1)
              .sort_values(0, ascending=True))
  xs = counted[0]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_22.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[2]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 2}, axis=1)
              .sort_values(2, ascending=True))
  xs = counted[2]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_23.sort_values(2, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(2)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_24[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_25[2].plot(kind='line', figsize=(8, 4), title=2)
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
df2.loc[0]

0    2
1    5
2    3
Name: 0, dtype: int64

In [ ]:
df2.loc[[0,2]]

0  1   2
0  2  5   3
2  7  8  10

In [ ]:
df2 = pd.DataFrame(np.array([[None,5,3],[4,None,6],[7,8,None]]))
print(df2)
print(df2.shape)

      0     1     2
0  None     5     3
1     4  None     6
2     7     8  None
(3, 3)


In [ ]:
#df2.dropna()

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [ ]:
#df2.fillna(9)

0  1  2
0  9  5  3
1  4  9  6
2  7  8  9

In [ ]:
df2.fillna(df2.mean())

0    1    2
0  5.5  5.0  3.0
1  4.0  6.5  6.0
2  7.0  8.0  4.5

In [ ]:
df = pd.read_excel('/content/pokemon_data.xlsx')

In [ ]:
df


#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [ ]:
df.head(5)

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [ ]:
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64