In [ ]:
import numpy as np
myarr = np.array([[3,4,6,7,8]],np.int8)
print(myarr[0,1])

4


In [ ]:
myarr.shape

(1, 5)

In [ ]:
myarr.dtype

dtype('int8')

In [ ]:
myarr[0,2]=5

In [ ]:
myarr

array([[3, 4, 5, 7, 8]], dtype=int8)

#Array Creation: Conversion from other Python Structures

In [ ]:
listarray = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
listarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
listarray.size

15

In [ ]:
np.array({34,23,24,56,76})

array({34, 23, 24, 56, 76}, dtype=object)

In [ ]:
zeros = np.zeros((3,4))
zeros.shape

(3, 4)

In [ ]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(1,5,10)
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
emp = np.empty((2,3))
emp

array([[4.86578180e-310, 0.00000000e+000, 6.55032754e-310],
       [6.79038654e-313, 2.14321575e-312, 2.27053550e-312]])

In [ ]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
ide = np.identity(4)
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
x = [[1,2,3],[4,5,6],[7,8,9]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar.sum(axis=0)

array([12, 15, 18])

In [ ]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [ ]:
ar.nbytes

72

In [ ]:
one = np.array([1,2,3])

In [ ]:
one.max()

3

In [ ]:
one.argmax()

2

In [ ]:
one.min()

1

In [ ]:
one.argmin()

0

In [ ]:
one.argsort()

array([0, 1, 2])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Get the first element from the following array:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[2]+arr[3])

1
2
3
4
7


In [ ]:
#Access 2-D arrays
import numpy as np
ar = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',ar[0,1])
print('5th element on 2nd row:',ar[1,4])

2nd element on 1st row: 2
5th element on 2nd row: 10


In [ ]:
#Acccess 3-D arrays
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a[0,1,2])

6


In [ ]:
#Negative indexing, print the last element from the 2nd dim
import numpy as np
arra = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arra[-1,-1])

10


In [ ]:
#Slicing 1D array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
#Slicing 2D array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[2 3 4]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
#check the data type of an array
import numpy as np
arr = np.array([1,2,3,4])
arr1=np.array(['apple','banana','cherry'])
print(arr.dtype)
print(arr1.dtype)

int64
<U6


In [ ]:
#Creating Arrays With a Defined Data Type
import numpy as np
arr = np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#For i, u, f, S and U we can define size as well.
import numpy as np
arr = np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
#A non integer string like 'a' can not be converted to integer (will raise an error):
import numpy as np
arr = np.array(['a','2','3'],dtype='i')


ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#Converting Data Type on Existing Arrays
import numpy as np
arr = np.array([1.1,2.1,3.1])
newnarr=arr.astype('i')
print(newnarr)
print(newnarr.dtype)
print(arr)
print(arr.dtype)

[1 2 3]
int32
[1.1 2.1 3.1]
float64


In [ ]:
import numpy as np
arr = np.array([1.2,2.2,3.2])
nwar = arr.astype(int)
print(nwar)
print(nwar.dtype)

[1 2 3]
int64


In [ ]:
import numpy as np
arr= np.array([1,0,3])
na = arr.astype(bool)
print(na)
print(na.dtype)

[ True False  True]
bool


# **NumPy Array Copy vs View**

In [ ]:
#COPY:
import numpy as np
arr = np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#VIEW:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
x[1]=33
arr[0]=42
print(arr)
print(x)

[42 33  3  4  5]
[42 33  3  4  5]


In [ ]:
#Check if Array Owns its Data
import numpy as np
arr = np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


# **NumPy Array Shape**

In [ ]:
#Get the Shape of an Array
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


# NumPy Array Reshaping


In [ ]:
#Reshape From 1-D to 2-D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr= arr.reshape(4,3)
newar = arr.reshape(2,3,2)
print(newar)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Can We Reshape Into any Shape?
#Yes, as long as the elements required for reshaping are equal in both shapes.

#We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
#Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,4)
print(newarr)
na=arr.reshape(3,3)
print(na)


[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
#Returns Copy or View?
#Check if the returned array is a copy or a view:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
#Unknown Dimension
#You are allowed to have one "unknown" dimension.

#Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

#Pass -1 as the value, and NumPy will calculate this number for you.
#Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Flattening the arrays
#Flattening array means converting a multidimensional array into a 1D array.
#We can use reshape(-1) to do this.
#Convert the array into a 1D array:

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
nwar=arr.reshape(-1)
print(nwar)

[1 2 3 4 5 6]


# Iterating Arrays

In [ ]:
#Iterate on the elements of the following 1-D array:
import numpy as np
arr = np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [ ]:
#Iterating 2-D Arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  print(x)


[1 2 3]
[4 5 6]


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
#Iterating Arrays Using nditer()
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np
arr = np.arra([1,2,3])
for x in np.nditer()